export const CREATEWBS ='CREATEWBS';
export const SAVE_AS_TEMPLATE='SAVE_AS_TEMPLATE';
export const SAVE_AS_TEMPLATE_COMPLETE = 'SAVE_AS_TEMPLATE_COMPLETE';
export const FETCH_TEMPLATES='FETCH_TEMPLATES';
export const FETCH_TEMPLATES_COMPLETE='FETCH_TEMPLATES_COMPLETE';
export const DELETE_TEMPLATE ='DELETE_TEMPLATE';