export const CREATE_ROOM = 'CREATE_ROOM';
export const FETCH_ROOMS = 'FETCH_ROOMS';
export const DELETE_ROOMS ='DELETE_ROOMS';
export const POST_MESSAGE ='POST_MESSAGE';
export const RECIEVE_MESSAGE ='RECIEVE_MESSAGE'; 
export const FETCH_ROOMS_COMPLETE ='FETCH_ROOMS_COMPLETE';