export const CREATE_ACCOUNT ='CREATE_ACCOUNT';
export const UPDATE_ACCOUNT='UPDATE_ACCOUNT';
export const DELETE_ACCOUNT='DELETE_ACCOUNT';
export const FETCH_ACCOUNT='FETCH_ACCOUNT';
export const FETCH_ACCOUNT_COMPLETE ='FETCH_ACCOUNT_COMPLETE';
export const UPDATE_ACCOUNT_COMPLETE ='UPDATE_ACCOUNT_COMPLETE';
export const SAVE_AS_TEMPLATE ='SAVE_AS_TEMPLATE';

export const FETCH_TEMPLATES ='FETCH_TEMPLATES';
export const FETCH_TEMPLATES_COMPLETE ='FETCH_TEMPLATES_COMPLETE';