export const POST_TABLE='POST_TABLE';
export const POST_TABLE_SUCCESSFUL='POST_TABLE_SUCCESSFUL';
export const FETCH_TABLES='FETCH_TABLES';
export const FETCH_TABLES_COMPLETE = 'FETCH_TABLES_COMPLETE';